// Typst template for the "by the numbers" county reports.
//
// Structure follows the R for the Rest of Us Quarto + Typst tutorial
// (https://rfortherestofus.com/2025/11/quarto-typst-pdf): report.qmd lists
// this file and typst-show.typ under template-partials; typst-show.typ calls
// report() with the document's YAML metadata; the helper functions below are
// called from report.qmd, both directly and from R chunks that emit raw
// Typst.

// ---- Palette ----
// Keep in sync with the palette in R/data-viz.R, which colors the chart marks.
#let focus-color = rgb("#4C7A2F")
#let focus-fill = rgb("#A8C686")
#let other-color = rgb("#B3B3B3")
#let ink = rgb("#333333")

// ---- Helpers ----

// Green highlight pill for the focus county. Doubles as an inline legend key
// for the green marks in the charts.
#let hl(body) = box(
  fill: focus-color,
  radius: 0.2em,
  inset: (x: 0.35em, y: 0.1em),
  baseline: 0.25em,
  text(fill: white, body),
)

// Gray pill: inline legend key for the gray context marks (state figures,
// other counties).
#let hl-gray(body) = box(
  fill: other-color,
  radius: 0.2em,
  inset: (x: 0.35em, y: 0.1em),
  baseline: 0.25em,
  text(fill: ink, body),
)

// Big-number stat tile.
#let stat(number, label) = block(width: 100%, inset: (y: 0.2em))[
  #text(size: 26pt, weight: "bold", fill: focus-color, number) \
  #text(size: 9pt, fill: luma(40%), upper(label))
]

// Section title + optional subtitle, replacing in-chart ggplot titles.
#let section-title(title, subtitle: none) = block(above: 1.6em, below: 0.9em)[
  #text(size: 14pt, weight: "bold", title)
  #if subtitle != none [
    \ #text(size: 9pt, fill: luma(40%), subtitle)
  ]
]

// One county/population pair in the population table; the focus county is
// bold and green.
#let county-cell(name, pop, focus: false) = {
  let style = if focus { (weight: "bold", fill: focus-color) } else { (:) }
  (
    align(left, text(..style, name)),
    align(right, text(..style, pop)),
  )
}

// Column headers for the population table.
#let th-left(t) = align(left, text(size: 8pt, fill: luma(40%), upper(t)))
#let th-right(t) = align(right, text(size: 8pt, fill: luma(40%), upper(t)))

// The county population table: n-cols county/population pairs side by side,
// separated by spacer columns. The cell stream (county-cell calls plus []
// spacers and padding) is generated by an R chunk in report.qmd; this
// function builds the matching column spec and header row.
#let population-table(n-cols, ..cells) = {
  let cols = ()
  let header = ()
  for i in range(n-cols) {
    if i > 0 {
      cols.push(0.25in)
      header.push([])
    }
    cols += (1fr, auto)
    header += (th-left[County], th-right[Population])
  }
  set text(size: 8.5pt)
  table(
    columns: cols,
    stroke: none,
    inset: (x: 0pt, y: 0.35em),
    table.header(..header),
    table.hline(stroke: 0.5pt + luma(70%)),
    ..cells.pos(),
  )
}

// Sources / methodology note for the bottom of the last page.
#let sources-note(acs-range, generated-date) = {
  line(length: 100%, stroke: 0.5pt + luma(85%))
  v(0.5em)
  text(size: 8pt, fill: luma(40%))[
    *Sources and notes.* All figures are American Community Survey 5-year
    estimates (#acs-range; tables B01003, B19013, and B03002), retrieved via
    the Census Bureau API. Boundaries are Census cartographic files. Estimates
    carry margins of error, not shown. Report generated #generated-date.
  ]
}

// ---- The report template ----
// county and state arrive from the document YAML via typst-show.typ. The
// report is branded to the state (band, footer); the county names the
// profile page below the band.
#let report(
  county: none,
  state: none,
  content,
) = {
  // The x margin puts the body content on the same left edge as the header
  // band's text, which is what makes the band read as part of the same grid.
  set page(
    paper: "us-letter",
    margin: (x: 1.35in, top: 0.75in, bottom: 0.9in),
    footer: context [
      #set text(size: 8pt, fill: gray)
      #state: By the Numbers
      #h(1fr)
      #counter(page).display()
    ],
  )
  set text(font: "Helvetica Neue", size: 10pt, fill: ink)
  set par(leading: 0.6em, justify: false)

  // Header band, bleeding to the top and side page edges. Zero x inset keeps
  // the band's text on the content grid's left edge.
  block(
    width: 100%,
    fill: focus-color,
    inset: (x: 0in, bottom: 0.35in, top: 0.1in),
    outset: (x: 1.35in, top: 0.75in),
  )[
    #text(fill: white, size: 26pt, weight: "bold")[#state] \
    #text(fill: focus-fill, size: 16pt, weight: "medium")[By the Numbers] \
    #v(0.2em)
    #text(fill: white.transparentize(25%), size: 9pt)[
      A demographic and economic profile from the American Community Survey
      (5-year estimates)
    ]
  ]

  v(0.25in)

  // This page's county profile.
  text(size: 20pt, weight: "bold", fill: focus-color)[#county County]

  v(0.1in)

  content
}
